version: "3.1"

# Example 1
# same as: docker run -p 8080:8080 -v $(PWD):/site bretfisher/jekyll-serve
services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:site
    ports:
      - "80:4000"


  # example 2
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: example
    ports:
      - "8080:80"  # or 8080:80
    volumes:
      - ./wordpress-data:/var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql-data:/var/lib/mysql